//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyaSyaDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int AttributeID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual AttributeCategory AttributeCategory { get; set; }
    }
}
